# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-01 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travel', '0021_auto_20180801_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personalized',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('FirstName', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=10)),
                ('City', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=4)),
                ('Date', models.DateField()),
                ('Language', models.CharField(max_length=20)),
                ('Cellnumber', models.CharField(max_length=20)),
                ('SNSID', models.CharField(max_length=15)),
                ('Content', models.TextField()),
                ('Price', models.CharField(max_length=15)),
                ('Guest', models.PositiveIntegerField()),
                ('Nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.Country')),
            ],
        ),
        migrations.CreateModel(
            name='SNS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='personalized',
            name='SNS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personalized.SNS'),
        ),
    ]
