# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-11 06:53
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personalized',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('FirstName', models.CharField(max_length=20)),
                ('Gender', models.CharField(choices=[('Man', 'Man'), ('Woman', 'Woman'), ('Other', 'Other')], max_length=10)),
                ('City', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'only number')])),
                ('Date', models.DateField()),
                ('Language', models.CharField(max_length=20)),
                ('Cellnumber', models.CharField(blank=True, max_length=20, null=True)),
                ('SNSID', models.CharField(max_length=15)),
                ('Content', models.TextField()),
                ('Price', models.CharField(max_length=15)),
                ('Guest', models.PositiveIntegerField()),
                ('confirm', models.BooleanField(default=False)),
                ('Nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Country')),
                ('SNS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.SNS')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalizedTour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('DetailContent', models.CharField(help_text='당신이 만든 local 여행에 대한 설명을 자유롭게 작성해 주세요.<br>Tip. 당신의 Tour만이 가지고 있는 특징에 대해 설명해주세요. 외국인은 언제나 local다움과 funny한 상품을 찾고 있습니다.', max_length=1200)),
                ('BriefContent', models.TextField(max_length=250)),
                ('HashTag', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('MeetingPoint', models.CharField(max_length=130)),
                ('Map', models.CharField(max_length=140)),
                ('Direction', models.CharField(max_length=200)),
                ('Price', models.CharField(max_length=10)),
                ('Minimum', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('Maximum', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('Price_include', models.CharField(max_length=100)),
                ('NotDate', models.TextField(blank=True)),
                ('GuestInfo', models.CharField(max_length=100)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('representation', models.NullBooleanField()),
                ('confirm', models.NullBooleanField()),
                ('SeasonFrom', models.DateField()),
                ('SeasonTo', models.DateField()),
                ('City', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.City')),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Personalized_country', to='accounts.Country')),
                ('Duration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.Duration')),
                ('Language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.Language')),
                ('MeetingTime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.Time')),
                ('Tourtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.TypeOfTour')),
                ('content', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Personalized.Personalized')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
