# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-11 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Personalized', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalizedtour',
            name='content',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personalized', to='Personalized.Personalized'),
        ),
    ]
