# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-01 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Personalized', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalized',
            name='Gender',
            field=models.CharField(choices=[('Man', 'Man'), ('Woman', 'Woman')], max_length=10),
        ),
        migrations.AlterField(
            model_name='personalized',
            name='SNS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.SNS'),
        ),
        migrations.DeleteModel(
            name='SNS',
        ),
    ]
