# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-01 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personalized', '0002_auto_20180801_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalized',
            name='Cellnumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
