# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-11 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Personalized', '0002_auto_20180812_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalized',
            name='confirm',
        ),
        migrations.RemoveField(
            model_name='personalizedtour',
            name='representation',
        ),
    ]
