# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-13 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personalized', '0003_auto_20180812_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalized',
            name='Date',
            field=models.CharField(max_length=100),
        ),
    ]
