# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-11 06:53
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LastName', models.CharField(max_length=20)),
                ('FirstName', models.CharField(max_length=20)),
                ('Age', models.PositiveIntegerField()),
                ('gender', models.CharField(blank=True, choices=[('Man', 'Man'), ('Woman', 'Woman'), ('Other', 'Other')], max_length=10, null=True)),
                ('Email', models.EmailField(max_length=30)),
                ('Date', models.DateField()),
                ('SNSID', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('ConfirmedEmail', models.EmailField(max_length=30)),
                ('Demand', models.CharField(max_length=1200)),
                ('NOP', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=15)),
                ('video', models.URLField(blank=True, null=True)),
                ('img', models.ImageField(upload_to='')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('DetailContent', models.CharField(help_text='당신이 만든 local 여행에 대한 설명을 자유롭게 작성해 주세요.<br>Tip. 당신의 Tour만이 가지고 있는 특징에 대해 설명해주세요. 외국인은 언제나 local다움과 funny한 상품을 찾고 있습니다.', max_length=1200)),
                ('BriefContent', models.TextField(max_length=250)),
                ('HashTag', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('MeetingPoint', models.CharField(max_length=130)),
                ('Map', models.CharField(max_length=140)),
                ('Direction', models.CharField(max_length=200)),
                ('Price', models.CharField(max_length=10)),
                ('Minimum', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('Maximum', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('Price_include', models.CharField(max_length=100)),
                ('NotDate', models.TextField(blank=True)),
                ('GuestInfo', models.CharField(max_length=100)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('representation', models.NullBooleanField()),
                ('confirm', models.NullBooleanField()),
                ('SeasonFrom', models.DateField()),
                ('SeasonTo', models.DateField()),
                ('City', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.City')),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_country', to='accounts.Country')),
                ('Duration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.Duration')),
                ('Language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.Language')),
            ],
        ),
        migrations.CreateModel(
            name='SNS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfTour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='MeetingTime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.Time'),
        ),
        migrations.AddField(
            model_name='post',
            name='Tourtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.TypeOfTour'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='Language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.Language'),
        ),
        migrations.AddField(
            model_name='booking',
            name='Nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Country'),
        ),
        migrations.AddField(
            model_name='booking',
            name='SNS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.SNS'),
        ),
        migrations.AddField(
            model_name='booking',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.Post'),
        ),
    ]
