# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 20:49
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('DetailContent', models.CharField(help_text='당신이 만든 local 여행에 대한 설명을 자유롭게 작성해 주세요.<br>Tip. 당신의 Tour만이 가지고 있는 특징에 대해 설명해주세요. 외국인은 언제나 local다움과 funny한 상품을 찾고 있습니다.', max_length=1200)),
                ('BriefContent', models.CharField(max_length=250)),
                ('HashTag', models.CharField(max_length=20)),
                ('img', models.ImageField(upload_to='')),
                ('MeetingPoint', models.CharField(max_length=50)),
                ('MeetingTime', models.CharField(max_length=30)),
                ('Map', models.CharField(max_length=10)),
                ('Direction', models.CharField(max_length=200)),
                ('CourseName', models.CharField(max_length=40)),
                ('Duration', models.CharField(max_length=20)),
                ('Price', models.CharField(max_length=10)),
                ('Minimum', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('Maximum', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('Price_include', models.CharField(max_length=100)),
                ('NotDate', models.DateField()),
                ('GuestInfo', models.CharField(max_length=100)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('representation', models.BooleanField()),
                ('confirm', models.BooleanField()),
                ('City', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.City')),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.Country')),
                ('Language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.Language')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfTour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='Tourtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.TypeOfTour'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.Country'),
        ),
    ]
