# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-22 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='SeasonFrom',
            field=models.DateField(default='2018-12-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='SeasonTo',
            field=models.DateField(default='2018-12-12'),
            preserve_default=False,
        ),
    ]
