# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-20 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_auto_20180812_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='GuestInfo',
            field=models.CharField(max_length=1000),
        ),
    ]
