# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-24 19:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_auto_20180723_0318'),
        ('travel', '0003_auto_20180725_0324'),
    ]

    operations = [
    ]
