# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-15 04:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_auto_20180713_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LastName', models.CharField(max_length=20)),
                ('FirstName', models.CharField(max_length=20)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=30)),
                ('Date', models.DateField()),
                ('phone', models.CharField(max_length=15)),
                ('ConfirmedEmail', models.EmailField(max_length=30)),
                ('Language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SNS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='Maximum',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='Minimum',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='booking',
            name='Nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.Nationality'),
        ),
        migrations.AddField(
            model_name='booking',
            name='SNS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.SNS'),
        ),
    ]
