# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-25 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_auto_20180725_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.Post'),
        ),
    ]
