# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-16 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_auto_20180715_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Major', models.CharField(max_length=30)),
                ('Interest', models.CharField(max_length=30)),
                ('Language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.Language')),
                ('NextCountry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Next', to='travel.Country')),
                ('VisitedCountry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Visited', to='travel.Country')),
            ],
        ),
    ]
