# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-16 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='representation',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
