# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-17 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_post_representation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Language',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='Nationality',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='SNS',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Language',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='NextCountry',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='VisitedCountry',
        ),
        migrations.AddField(
            model_name='post',
            name='confirm',
            field=models.BooleanField(default='False'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Nationality',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='SNS',
        ),
    ]
