# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-25 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_auto_20180725_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Age',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
