# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-26 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_auto_20180725_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='NOP',
            field=models.PositiveIntegerField(default='1'),
            preserve_default=False,
        ),
    ]
