# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-27 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_booking_nop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Age',
            field=models.PositiveIntegerField(default='0'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='booking',
            name='Nationality',
        ),
        migrations.AddField(
            model_name='booking',
            name='Nationality',
            field=models.ManyToManyField(to='travel.Country'),
        ),
    ]
