# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-27 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_auto_20180727_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Nationality',
        ),
        migrations.AddField(
            model_name='booking',
            name='Nationality',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='travel.Country'),
            preserve_default=False,
        ),
    ]
