# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-27 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_auto_20180727_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='Duration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.Duration'),
        ),
        migrations.AlterField(
            model_name='post',
            name='MeetingTime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.Time'),
        ),
    ]
