# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-28 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0013_auto_20180727_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeoftour',
            name='img',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
