# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-30 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0014_typeoftour_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='NotDate',
            field=models.TextField(),
        ),
    ]
