# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-30 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0015_auto_20180730_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='NotDate',
            field=models.DateField(),
        ),
    ]
