# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-31 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0017_auto_20180730_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Map',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='post',
            name='Photography',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
