# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-01 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0020_auto_20180801_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='BriefContent',
            field=models.TextField(max_length=250),
        ),
    ]
