# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-06 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Personalized', '0004_auto_20180807_0219'),
        ('travel', '0021_auto_20180801_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Country'),
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Country'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_country', to='accounts.Country'),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
