# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-07 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0022_auto_20180807_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='BriefCourse',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='HashTag',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='MeetingPoint',
            field=models.CharField(max_length=130),
        ),
    ]
