# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-20 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='image',
            field=models.ImageField(upload_to='Country/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nextCountry',
            field=models.ManyToManyField(blank=True, related_name='Next', to='accounts.Country'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='video',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='visitedCountry',
            field=models.ManyToManyField(blank=True, related_name='Visited', to='accounts.Country'),
        ),
    ]
