# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-21 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180720_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='sdf', max_length=10),
            preserve_default=False,
        ),
    ]
