# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-27 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180721_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nextCountry',
        ),
        migrations.AddField(
            model_name='profile',
            name='nextCountry',
            field=models.ManyToManyField(blank=True, null=True, related_name='Next', to='accounts.Country'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='visitedCountry',
        ),
        migrations.AddField(
            model_name='profile',
            name='visitedCountry',
            field=models.ManyToManyField(blank=True, null=True, related_name='Visited', to='accounts.Country'),
        ),
    ]
