# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-27 02:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180727_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nextCountry',
        ),
        migrations.AddField(
            model_name='profile',
            name='nextCountry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Next', to='accounts.Country'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='visitedCountry',
        ),
        migrations.AddField(
            model_name='profile',
            name='visitedCountry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Visited', to='accounts.Country'),
        ),
    ]
