# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-29 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
