# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-06 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20180806_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='visitedCountry',
        ),
        migrations.AddField(
            model_name='profile',
            name='visitedCountry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Visited', to='accounts.Country'),
        ),
    ]
