# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-06 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20180806_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nextCountry',
        ),
        migrations.AddField(
            model_name='profile',
            name='nextCountry',
            field=models.ManyToManyField(blank=True, null=True, related_name='Next', to='accounts.Country'),
        ),
    ]
