# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-17 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LastName', models.CharField(max_length=20)),
                ('FirstName', models.CharField(max_length=20)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=30)),
                ('Date', models.DateField()),
                ('phone', models.CharField(max_length=15)),
                ('ConfirmedEmail', models.EmailField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SNS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='Language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Booking.Language'),
        ),
        migrations.AddField(
            model_name='booking',
            name='Nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Booking.Nationality'),
        ),
        migrations.AddField(
            model_name='booking',
            name='SNS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Booking.SNS'),
        ),
    ]
