# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-18 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Demand',
            field=models.CharField(default='', max_length=1200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='SNSID',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nationality',
            name='image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
