# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-23 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_auto_20180718_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Gender',
        ),
        migrations.AddField(
            model_name='booking',
            name='gender',
            field=models.CharField(blank=True, choices=[('Man', 'Man'), ('Woman', 'Woman')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Age',
            field=models.PositiveIntegerField(),
        ),
    ]
